apiVersion: v1
kind: Service
metadata:
  name: spring-backend
  namespace: assignment
  labels:
    service: spring-backend
    project: assignment
spec:
  type: NodePort
  selector:
    service: spring-backend
    project: assignment
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  namespace: assignment
spec:
  selector:
    matchLabels:
      service: spring-backend
      project: assignment
  template:
    metadata:
      labels:
        service: spring-backend
        project: assignment
    spec:
      containers:
        - name: spring-backend
          image: nylonmusk/spring-project-2
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://database:3306/assignment
            - name: SPRING_DATASOURCE_USERNAME
              value: test
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "2Gi"